build: 'off'
environment:
  matrix:
    - nodejs_version: '6'
install:
  - ps: 'Install-Product node $env:nodejs_version'
  - npm install
  - npm install --global flow-typed
  - flow-typed install
test_script:
  - node --version
  - npm --version
  - npm cache clean
  - npm test
