build: 'off'
environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '11'
install:
  - ps: 'Install-Product node $env:nodejs_version x64'
  - npm install --global npm-windows-upgrade
  - npm-windows-upgrade --no-spinner --npm-version latest
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
