// flow-typed signature: 3b75f59bc705ed7fcff2097f200385c0
// flow-typed version: <<STUB>>/boxen_v^0.8.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boxen'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'boxen' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'boxen/index' {
  declare module.exports: $Exports<'boxen'>;
}
declare module 'boxen/index.js' {
  declare module.exports: $Exports<'boxen'>;
}
