// flow-typed signature: 0862e9a49745c2f872d2a12c55632dc4
// flow-typed version: <<STUB>>/clear-require_v^1.0.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clear-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clear-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'clear-require/index' {
  declare module.exports: $Exports<'clear-require'>;
}
declare module 'clear-require/index.js' {
  declare module.exports: $Exports<'clear-require'>;
}
